var list = NewList.GenerateNumbers(1, 100);
Console.WriteLine(NewList.CalculateSum(list));
list = NewList.InsertSumAfterPairs(list);
Console.WriteLine(NewList.CalculateSum(list));
list = NewList.RemoveEvenNumbers(list);
Console.WriteLine(NewList.CalculateSum(list));
list = NewList.ReplaceWithRunningTotal(list);
Console.WriteLine(NewList.CalculateSum(list));
long result = NewList.CalculateResult(list);
Console.WriteLine($"Result: {result}");